imports:
    - { resource: '@DelPlopUserBundle/config/packages/security.yaml' }

security:
    access_control:
        - { path: ^/communaute/compagnons, roles: ROLE_USER }
        - { path: ^/communaute/(consulter|contacter|modifier)/compagnon/\d+, roles: ROLE_USER }
        - { path: ^/communaute/compagnon/cartes-(possedees|recherchees)/\d+, roles: ROLE_USER }
        - { path: ^/communaute/compagnon/(possede|recherche)-carte/\d+, roles: ROLE_USER }
        - { path: ^/communaute/compagnon/stop-(possede|recherche)-carte/\d+, roles: ROLE_USER }
        - { path: ^/communaute/compagnon/export-cartes-(possedees|recherchees)/\d+, roles: ROLE_USER }
        - { path: ^/carte-(possedee|recherchee)/\d+/sauver, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }
