#imports:
#    - { resource: '../../vendor/delplop/userbundle/config/packages/symfonycasts_reset_password.yaml' }

symfonycasts_reset_password:
  request_password_repository: DelPlop\UserBundle\Repository\ResetPasswordRequestRepository
