twig:
    default_path: '%kernel.project_dir%/templates'

#    paths:
#        '%kernel.project_dir%/vendor/delplop/wishlistbundle/src/Resources/views': DelPlopWishList

when@test:
    twig:
        strict_variables: true
