index:
    path: /
    controller: App\Controller\IndexController::index
    methods: GET

login:
    path: /connexion
    controller: App\Controller\SecurityController::login
    methods: [GET, POST]

logout:
    path: /deconnexion
    controller: App\Controller\SecurityController::logout
    methods: GET

register:
    path: /inscription
    controller: App\Controller\RegistrationController::register
    methods: [GET, POST]
