parameters:
    router.request_context.scheme: 'https'
    asset.request_context.secure: true

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Controller\:
        resource: '../src/Controller/'
        tags: [ 'controller.service_arguments' ]

    project.subscriber.table_prefix:
        class: App\Subscriber\TablePrefixSubscriber
        arguments:
            $prefix: 'sf_'
        tags:
            - { name: doctrine.event_subscriber }
